services:
  event-api:
    build: .
    container_name: event-api-service
    networks:
      - proxy  # Traefik Netzwerk
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.event-api.rule=Host(`api.calentian.de`) && PathPrefix(`/event-api`)"
      - "traefik.http.routers.event-api.entrypoints=websecure"
      - "traefik.http.routers.event-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.event-api.loadbalancer.server.port=4000"  # Intern genutzter Port

    env_file:
      - ../calentian.env
    restart: always

networks:
  proxy:
    external: true
