services:
  data-storage-service:
    build:
      context: ..
      dockerfile: data-storage/Dockerfile
    container_name: data-storage-service
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.data-storage-service.rule=Host(`api.calentian.de`) && PathPrefix(`/data-storage`)"
      - "traefik.http.routers.data-storage-service.entrypoints=websecure"
      - "traefik.http.routers.data-storage-service.tls.certresolver=letsencrypt"
      - "traefik.http.services.data-storage-service.loadbalancer.server.port=4200"
    env_file:
      - .env
    restart: always

networks:
  proxy:
    external: true
