services:
  crm-server:
    build: .
    container_name: crm-service
    restart: always
    env_file:
      - ../calentian.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm-service.rule=Host(`api.calentian.de`) && PathPrefix(`/crm-service`)"
      - "traefik.http.routers.crm-service.entrypoints=websecure"
      - "traefik.http.routers.crm-service.tls.certresolver=letsencrypt"
      - "traefik.http.services.crm-service.loadbalancer.server.port=6203"
    networks:
      - proxy
networks:
  proxy:
    external: true
